### PR TITLE
Wrote dice trigger

### PR DESCRIPTION
**Pull request by parsec**

### CODE REVIEW

**Comment by parsec** [comment]
Okay, so, here's the problem it's pointing out:

```
#12 1.003 dice.go:7:2: no required module provides package github.com/justinian/dice; to add it:
#12 1.003 	go get github.com/justinian/dice
#12 ERROR: executor failed running [/bin/sh -c ./docker-build.sh]: exit code: 1
```

Except, yano, since it's an ephemeral build environment I can't exactly run `go get`, now can I? Any ideas, y'all? I tried adding it manually to `go.mod`, it didn't like that (I assume that's bad practice).

**Comment by parsec** [comment]
Based on cursory research, it looks like Go expects everything to be a module now. So, I guess this means I might need to fork the dependency and take over development to make it a module. It's not been updated in awhile so, no time like the present. That sound accurate?

https://stackoverflow.com/questions/66267267/no-required-module-provides-package-sdl2
https://blog.golang.org/go116-module-changes

**Review by m-242 — CHANGES_REQUESTED** [review]
Looks like you forgot to `go fmt ./...`

Also, we probably don't want the DICE_USAGE constant in the main package.

**Comment by parsec** [comment]
> Also, we probably don't want the DICE_USAGE constant in the main package.

where would be better you think? inside the func?

**Comment by parsec** [comment]
It's still mad that nothing provides the dice library, but like... I don't understand. I'm not understanding why it isn't grabbing the library when it builds it. And I'm not sure if I'm supposed to run `go get` or because it's built elsewhere if that does anything for me

**Pull request merged**
